global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'buzzer'
    metrics_path: '/metrics-micrometer'
    static_configs:
      - targets: [ 'buzzer:8080' ]
        labels:
          application: 'web-buzzer'