services:
  buzzer:
    image: "localhost:5000/web-buzzer"
    container_name: buzzer
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - monitoring-network
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring-network
    depends_on:
      - buzzer

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local